modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL=""

[[mods]]
modId="{{ ModName }}"
version="${file.jarVersion}"
displayName="{{ ModName }}"
displayURL=""
authors="FireBall1725"
description=""

[[dependencies.{{ ModName }}]]
  modId="forge"
  mandatory=true
  versionRange="[28,)"
  ordering="NONE"
  side="CLIENT"

[[dependencies.{{ ModName }}]]
  modId="minecraft"
  mandatory=true
  versionRange="[1.14.4]"
  ordering="NONE"
  side="CLIENT"
