modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL=""

[[mods]]
modId="{CHANGEME:ModName}"
version="${file.jarVersion}"
displayName="{CHANGEME:ModName}"
displayURL=""
authors="FireBall1725"
description=""

[[dependencies.{CHANGEME:ModName}]]
  modId="forge"
  mandatory=true
  versionRange="[28,)"
  ordering="NONE"
  side="CLIENT"

[[dependencies.{CHANGEME:ModName}]]
  modId="minecraft"
  mandatory=true
  versionRange="[1.14.4]"
  ordering="NONE"
  side="CLIENT"
